import pandas as pd
import gradio as gr
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import urllib.parse
import ast
import random
import os

# ======================
# LLM / RAG INTEGRATION
# ======================

USE_LLM = False
llm_model = None

try:
    import google.generativeai as genai
    
    # Try to get API key from environment variable
    api_key ="AIzaSyCUng8JOXiMM6hP5DaREUcM3WIPmKab66I"
    
    if api_key:
        genai.configure(api_key=api_key)
        llm_model = genai.GenerativeModel("gemini-2.5-flash-exp")
        USE_LLM = True
        print("✅ RAG System Enabled: Gemini AI connected")
        print("   Natural language responses will be generated by LLM")
    else:
        print("ℹ️  No GEMINI_API_KEY found in environment")
        print("   Using template-based responses (original mode)")
        print("   To enable RAG: Set environment variable GEMINI_API_KEY")
except ImportError:
    print("ℹ️  google-generativeai not installed")
    print("   Install with: pip install google-generativeai")
    print("   Using template-based responses (original mode)")
except Exception as e:
    print(f"ℹ️  Gemini initialization failed: {str(e)}")
    print("   Using template-based responses (original mode)")

# ======================
# RAG: LLM RESPONSE GENERATION
# ======================

def generate_llm_response(user_query, movie, genre, similarity_score):
    """
    RAG-based response generation using LLM
    
    RAG Pipeline:
    1. RETRIEVAL: Movie retrieved via TF-IDF + Cosine Similarity (already done)
    2. AUGMENTATION: Build context with movie metadata
    3. GENERATION: LLM generates personalized natural language response
    """
    
    if not USE_LLM or llm_model is None:
        # Fallback to template-based response
        return generate_template_response(user_query, movie, genre, similarity_score)
    
    try:
        # Build rich context for LLM (AUGMENTATION phase)
        context = f"""
You are an enthusiastic movie recommendation assistant. A user asked: "{user_query}"

Based on their request, I retrieved this movie from my database:

**Movie Title:** {movie.title}
**Genres:** {movie.genre_names}
**Rating:** {movie.vote_average}/10
**Match Score:** {similarity_score:.2f} (how well it matches their request)
**Plot Summary:** {movie.overview[:400]}

Your task:
1. Greet them warmly and acknowledge their request
2. Introduce the movie with enthusiasm
3. Explain in 2-3 sentences WHY this movie matches what they asked for
4. Highlight key aspects (genre, plot elements, mood)
5. Include the rating and mention it's a great match
6. End with an encouraging call-to-action

Keep it conversational, friendly, and under 200 words. Use emojis sparingly (1-2 max).
Format with clear line breaks for readability.
"""
        
        # GENERATION: Call LLM
        response = llm_model.generate_content(context)
        llm_text = response.text.strip()
        
        # Add trailer link (this part stays the same)
        query = f"{movie.title} official trailer"
        trailer_link = "https://www.youtube.com/results?search_query=" + urllib.parse.quote(query)
        
        # Combine LLM response with trailer link
        full_response = (
            f"{llm_text}\n\n"
            f"▶️ **[Watch Trailer on YouTube]({trailer_link})**\n\n"
            f"_({len(recommended_movies)} movies recommended so far | Say 'reset' to clear)_"
        )
        
        return full_response
        
    except Exception as e:
        print(f"⚠️  LLM generation failed: {str(e)}")
        print("   Falling back to template response")
        return generate_template_response(user_query, movie, genre, similarity_score)

def generate_template_response(user_query, movie, genre, similarity_score):
    """
    Original template-based response (fallback when LLM not available)
    """
    query = f"{movie.title} official trailer"
    trailer_link = "https://www.youtube.com/results?search_query=" + urllib.parse.quote(query)
    
    response = (
        f"🎬 **Recommended Movie:** {movie.title}\n\n"
        f"⭐ **Rating:** {movie.vote_average}/10\n\n"
        f"🎭 **Genres:** {movie.genre_names}\n\n"
        f"📝 **Overview:**\n{movie.overview[:350]}...\n\n"
        f"▶️ **[Watch Trailer on YouTube]({trailer_link})**\n\n"
        f"_({len(recommended_movies)} movies recommended so far | Say 'reset' to clear)_"
    )
    
    return response

# ======================
# LOAD DATASET
# ======================
df = pd.read_csv("tmdb_5000_movies.csv")

# Keep required columns
df = df[
    ["title", "overview", "genres", "original_language", "production_countries", "vote_average"]
].dropna()

# ======================
# EXTRACT GENRE NAMES
# ======================
def extract_genres(genres_str):
    """Extract clean genre names from JSON string"""
    try:
        genres_list = ast.literal_eval(genres_str)
        return [g['name'].lower() for g in genres_list]
    except:
        return []

def get_genre_string(genres_str):
    """Get space-separated genre string"""
    try:
        genres_list = ast.literal_eval(genres_str)
        return ' '.join([g['name'] for g in genres_list])
    except:
        return ""

df['genre_list'] = df['genres'].apply(extract_genres)
df['genre_names'] = df['genres'].apply(get_genre_string)

# ======================
# DETECT BOLLYWOOD
# ======================
def is_bollywood(row):
    if row["original_language"] == "hi":
        return True
    if "India" in str(row["production_countries"]):
        return True
    return False

df["is_bollywood"] = df.apply(is_bollywood, axis=1)

# ======================
# CREATE ENHANCED DOCUMENTS
# ======================
documents = (
    "Title: " + df["title"] + " " +
    df["genre_names"] + " " + df["genre_names"] + " " +
    "Overview: " + df["overview"]
).tolist()

# ======================
# DENSE RETRIEVAL WITH TF-IDF
# ======================
print("\nBuilding TF-IDF vectors for retrieval...")
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=1500,
    ngram_range=(1, 2)
)
doc_vectors = vectorizer.fit_transform(documents)
print("✓ Retrieval system ready!")

# ======================
# GENRE MAPPING
# ======================
GENRE_MAPPING = {
    'action': 'action',
    'romantic': 'romance',
    'romance': 'romance',
    'love': 'romance',
    'comedy': 'comedy',
    'funny': 'comedy',
    'laugh': 'comedy',
    'thriller': 'thriller',
    'suspense': 'thriller',
    'horror': 'horror',
    'scary': 'horror',
    'drama': 'drama',
    'emotional': 'drama',
    'crime': 'crime',
    'detective': 'crime',
    'adventure': 'adventure',
    'fantasy': 'fantasy',
    'magical': 'fantasy',
    'animation': 'animation',
    'animated': 'animation',
    'cartoon': 'animation',
    'scifi': 'science fiction',
    'sci-fi': 'science fiction',
    'science fiction': 'science fiction',
    'space': 'science fiction',
    'war': 'war',
    'western': 'western',
    'mystery': 'mystery',
    'family': 'family',
    'kids': 'family'
}

def extract_genre_from_query(query):
    """Extract genre from user query"""
    query_lower = query.lower()
    for keyword, genre in GENRE_MAPPING.items():
        if keyword in query_lower:
            return genre
    return None

# ======================
# GLOBAL MEMORY FOR RECOMMENDATIONS
# ======================
recommended_movies = set()

# ======================
# ENHANCED RETRIEVAL WITH MEMORY
# ======================
def retrieve_movie(query, avoid_bollywood=False, top_n=10):
    """
    RETRIEVAL Phase of RAG:
    Retrieve best matching movie with genre filtering and memory
    """
    
    # Extract requested genre
    requested_genre = extract_genre_from_query(query)
    
    # Compute similarity scores
    q_vec = vectorizer.transform([query])
    scores = cosine_similarity(q_vec, doc_vectors)[0]
    
    # Get top candidates
    ranked_indices = scores.argsort()[::-1][:100]
    
    candidates = []
    
    for idx in ranked_indices:
        movie = df.iloc[idx]
        
        # Skip if already recommended in this session
        if movie.title in recommended_movies:
            continue
        
        # Skip Bollywood if requested
        if avoid_bollywood and movie.is_bollywood:
            continue
        
        # If genre is specified, check if movie matches
        if requested_genre:
            movie_genres = movie.genre_list
            if not any(requested_genre in g for g in movie_genres):
                continue
        
        # Add to candidates with score
        candidates.append({
            'movie': movie,
            'score': scores[idx],
            'rating': movie.vote_average,
            'idx': idx
        })
        
        if len(candidates) >= top_n:
            break
    
    if not candidates:
        return None, None, None
    
    # Sort by combination of similarity score and rating
    candidates.sort(key=lambda x: x['score'] * 0.7 + (x['rating'] / 10) * 0.3, reverse=True)
    
    # Add some randomness to top 3 to vary recommendations
    if len(candidates) >= 3:
        selected = random.choice(candidates[:3])
    else:
        selected = candidates[0]
    
    # Remember this movie
    recommended_movies.add(selected['movie'].title)
    
    return selected['movie'], requested_genre, selected['score']

# ======================
# INTENT KEYWORDS
# ======================
INTENT_KEYWORDS = [
    "action", "romantic", "romance", "comedy", "funny",
    "thriller", "horror", "drama", "crime", "scary",
    "adventure", "fantasy", "animation", "scifi", "sci-fi",
    "mystery", "war", "western", "family", "love", "movie", "film"
]

# ======================
# CHATBOT FUNCTION WITH RAG
# ======================
def bot_response(message, history):
    """
    Main chatbot response function with RAG integration
    
    RAG Pipeline:
    1. Intent Detection
    2. RETRIEVAL: Find relevant movie using TF-IDF + Cosine Similarity
    3. AUGMENTATION: Prepare context with movie metadata
    4. GENERATION: LLM creates personalized response (or template fallback)
    """
    
    if not message or len(message.strip()) < 3:
        if USE_LLM:
            welcome = (
                "👋 Hello! I'm your **AI-powered** movie recommendation assistant.\n\n"
                "I use advanced language models to understand your preferences and suggest perfect movies!\n\n"
                "**Tell me what you're in the mood for:**\n"
                "• \"I want something funny and lighthearted\"\n"
                "• \"Recommend a thrilling action movie\"\n"
                "• \"Something romantic but not cheesy\"\n"
                "• \"A mind-bending sci-fi film\"\n\n"
                "💡 I'll give you personalized recommendations with natural explanations!"
            )
        else:
            welcome = (
                "👋 Hello! I'm your movie recommendation assistant.\n\n"
                "Tell me what kind of movie you want to watch!\n\n"
                "**Examples:**\n"
                "• Action movie\n"
                "• Romantic comedy\n"
                "• Horror film\n"
                "• Sci-fi adventure\n"
                "• Thriller movie"
            )
        return welcome

    msg = message.lower()

    # Check for reset command
    if "reset" in msg or "clear history" in msg:
        recommended_movies.clear()
        return "✅ Recommendation history cleared! You can now get fresh recommendations."

    # Check for genre intent
    if not any(word in msg for word in INTENT_KEYWORDS):
        return (
            "🤔 Please specify a genre or mood.\n\n"
            "**Examples:**\n"
            "• Recommend an action movie\n"
            "• I want a comedy film\n"
            "• Show me a horror movie\n"
            "• Suggest a romantic film"
        )

    # Check if user wants to avoid Bollywood
    avoid_bollywood = "not bollywood" in msg or "no bollywood" in msg or "avoid bollywood" in msg

    # RETRIEVAL Phase: Get movie recommendation
    movie, genre, similarity_score = retrieve_movie(message, avoid_bollywood)

    if movie is None:
        return (
            "❌ Sorry, I couldn't find a new movie matching your request.\n\n"
            f"(I've already recommended {len(recommended_movies)} movies)\n\n"
            "Try: a different genre or say 'reset' to clear history"
        )

    # AUGMENTATION + GENERATION Phase: Create response
    # This calls either LLM (if available) or template (fallback)
    response = generate_llm_response(message, movie, genre, similarity_score)
    
    return response

# ======================
# GRADIO UI
# ======================

# Customize description based on LLM availability
if USE_LLM:
    description = (
        "🤖 **RAG-Powered Movie Recommender** - Using Gemini AI for natural language responses\n\n"
        "✨ **RAG Pipeline:** Retrieval (TF-IDF) → Augmentation (Context) → Generation (LLM)\n\n"
        "🎯 **Features:** AI-generated explanations • Genre filtering • Memory system • Trailer links\n\n"
        "💡 **Tip:** Say 'reset' to clear recommendation history"
    )
else:
    description = (
        "🎯 Genre-based movie recommendations with memory - never repeats!\n\n"
        "✨ **Features:** Genre filtering • Rating-based ranking • Trailer links • Bollywood filtering\n\n"
        "💡 **Tip:** Say 'reset' to clear recommendation history\n\n"
        "ℹ️  Set GEMINI_API_KEY environment variable to enable AI-powered responses"
    )

demo = gr.ChatInterface(
    fn=bot_response,
    title="🎬 Smart Movie Recommendation Chatbot" + (" 🤖 (RAG-Enabled)" if USE_LLM else ""),
    description=description,
    examples=[
        "I want something thrilling and suspenseful",
        "Recommend a funny comedy to cheer me up",
        "Show me an emotional drama",
        "I need an action-packed adventure",
        "Suggest a romantic movie",
        "Find me a mind-bending sci-fi film",
        "reset"
    ]
)

if __name__ == "__main__":
    print("\n" + "="*60)
    print("🎬 MOVIE RECOMMENDATION SYSTEM")
    print("="*60)
    print(f"RAG Mode: {'✅ ENABLED (Using Gemini AI)' if USE_LLM else '❌ DISABLED (Template mode)'}")
    print(f"Dataset: {len(df)} movies loaded")
    print(f"Genres available: {df['main_genre'].nunique() if 'main_genre' in df.columns else 'Multiple'}")
    print("="*60)
    print("\nStarting Gradio interface...")
    
    demo.launch()